function AllChats(){
   return (
      <div className="bg-green-300">
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
        <h1>taiseer</h1>
      </div>
    );
}

export default AllChats;