export const moods = [
    { emoji: "😊", label: "Happy" },
    { emoji: "💪", label: "We Got This" },
    { emoji: "🥊", label: "Fighting" },
    { emoji: "⚡", label: "Energetic" },
    { emoji: "📖", label: "Studying" },
    { emoji: "💔", label: "Broken" },
    { emoji: "😩", label: "Exhausted" },
    { emoji: "😞", label: "Low Mood" },
    { emoji: "🤖", label: "Bot" },
    { emoji: "💼", label: "Busy" },
    { emoji: "🏠", label: "Chilling at Home" },
    { emoji: "👤", label: "Mysterious" },
    { emoji: "😴", label: "Sleeping" },
    { emoji: "🎮", label: "Gaming" },
    { emoji: "✅", label: "Checking-In" },
    { emoji: "🧋", label: "Milk Tea" },
    { emoji: "🌍", label: "Saving the World" },
    { emoji: "🚫", label: "Do Not Disturb" },
    { emoji: "🏋️", label: "Workout" },
    { emoji: "🍽️", label: "Eating" },
    { emoji: "🤳", label: "Taking Selfie" },
    { emoji: "🧘", label: "Meditating" },
    { emoji: "🐱", label: "Playing with a Cat" },
    { emoji: "🎵", label: "Music" },
  ];